FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY manage.py .
COPY config config
COPY apps apps

CMD python manage.py migrate && \
    python manage.py create_admin && \
    python manage.py collectstatic --noinput && \
    python manage.py runserver 0.0.0.0:8000
