FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING=UTF-8 \
    PIP_NO_CACHE_DIR=1

COPY requirements/requirements.txt requirements.txt
RUN pip install -U pip uv && uv pip install -r requirements.txt --system

COPY manage.py .
COPY config config
COPY apps apps

RUN python manage.py collectstatic --noinput

CMD ["sh", "-c", "\
    python manage.py migrate && \
    python manage.py create_admin && \
    gunicorn config.wsgi --bind 0.0.0.0:8000 --workers 2 \
"]
