FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING=UTF-8

COPY requirements/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY manage.py .
COPY config config
COPY apps apps

RUN python manage.py collectstatic --noinput

CMD ["sh", "-c", "\
    python manage.py migrate && \
    python manage.py create_admin && \
    python manage.py runserver 0.0.0.0:8000 \
"]
